version: '3'

tasks:
  tf-docs:
    desc: Generate terraform docs in README.md
    cmd: terraform-docs markdown table --output-file README.md --output-mode inject ./
  run-hooks:
    desc: Run pre-commit hooks on all files
    cmd: "pre-commit run --all-files"
  ansible-galaxy:
    desc: Run ansible galaxy install
    summary: |
      Run ansible-galaxy to install required packages
      Expects a requirements.yaml in the root of the project
    cmd: ansible-galaxy install -r requirements.yaml
    dir: '{{.USER_WORKING_DIR}}'
  install-tofu:
    desc: Install tofu version as defined in required_version
    summary: |
      Uses tenv to install the latest allowed version of tofu
      Needs to be run from tofu project directory and expects the project to have required_version set
    cmd: tenv tofu install latest-allowed
    dir: '{{.USER_WORKING_DIR}}'
  install-terraform:
    desc: Install terraform version as defined in required_version
    summary: |
      Uses tenv to install the latest allowed version of terraform
      Needs to be run from terraform project directory and expects the project to have required_version set
    cmd: tenv terraform install latest-allowed
    dir: '{{.USER_WORKING_DIR}}'