version: '3'

tasks:
  tf-docs:
    desc: Generate terraform docs in README.md
    cmd: terraform-docs markdown table --output-file README.md --output-mode inject ./
  run-hooks:
    desc: Run pre-commit hooks on all files
    cmd: "pre-commit run --all-files"
  ansible-galaxy:
    desc: Run ansible galaxy install
    summary: |
      Run ansible-galaxy to install required packages
      Expects a requirements.yaml in the root of the project
    cmd: ansible-galaxy install -r requirements.yaml
    dir: '{{.USER_WORKING_DIR}}'
