# This files was added by a devbox script from our devops tools project and is maintained there:
# https://github.com/onlinecity/devops-tools
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: 81e9f98ffd059efe8aa9c1b1a42e5cce61b640c6 # v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: c9646748faf2914cbac342e9c06a7b5865d06d2f # v1.89.1
    hooks:
      - id: terraform_tflint
  - repo: local
    hooks:
      - id: editorconfig-checker
        name: Check editorconfig is followed
        description: This hooks run editorconfig checking, ensuring editorconfig is followed in case the IDE doesn't do it automatically
        # editorconfig-checker accepts a config file `.ecrc` but it doesn't have to exist.
        entry: editorconfig-checker --config .ecrc
        language: system
