# This files was added by a devbox script from our devops tools project and is maintained there:
# https://github.com/onlinecity/devops-tools
name: Release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    uses: onlinecity/github-actions-shared-workflows/.github/workflows/release-please.yml@v1.4.1
    with:
      app-id: ${{ vars.APP_OC_GITHUB_RELEASE_PLEASE_ID }}
    secrets:
      app-pem: ${{ secrets.APP_OC_GITHUB_RELEASE_PLEASE_PEM }}
